### ISSUE TITLE
Добавить обработку якорей в ссылках

### ISSUE THREAD

**Issue by MrC0nst** [u236/homed-service-web#3]
Если якорь не обнаружен то просто переходить на /#zigbee
![image](https://github.com/u236/homed-service-web/assets/75075223/160084a9-1a91-4680-a5b9-760980644828)

**Comment by u236** [comment]
https://github.com/u236/homed-service-web/commit/39e2a4d4ad21e384f9ff29c6368fcd6f27dfe3b1
