### ISSUE TITLE
Добавить ссылку на WIKI из веб 8080

### ISSUE THREAD

**Issue by Blacksli** [u236/homed-service-web#4]
Добавить ссылку на WIKI из веб 8080, удобно для начинающих кто часто лазит смотреть конфиг итп

**Comment by Blacksli** [comment]
автор не рассматривает новые функции.

**Comment by u236** [comment]
уточнение - автор рассматривает новые функции, но оставляет за собой право решать, нужны ли они

**Comment by u236** [comment]
https://github.com/u236/homed-service-web/commit/2ec275a5e2f117d451d4d6d3807ebf907604549c
